//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS321Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class laptop
    {
        public int id { get; set; }
        public int year { get; set; }
        public string lmodel { get; set; }
        public string pmodel { get; set; }
        public string socket { get; set; }
        public string chipset { get; set; }
    }
}
